apiVersion: v1
kind: Service
metadata:
  name: assignment-service
spec:
  selector:
    app: assignment
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30111
  type: NodePort
